 - hosts: all
   become: yes
   tasks:
     - package:
           name:  "node"
           state: latest
     - name: "Git Checkout"
       ansible.builtin.git:
           repo: "https://github.com/reverentgeek/node-weight-tracker"
           dest: "/var/www/html/ws2"
